name: build-windows-exe
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build exe
        run: pyinstaller --noconsole --onefile --add-data "icon.ico;." app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: dist/reporter.exe
